name: notifi
description: A multi platform app to receive push notifications over simple HTTP requests you can embed anywhere.

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  app_settings: ^4.1.0
  cached_network_image: ^3.1.0
  desktop_window: ^0.4.0
  dio: ^4.0.0
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  flutter:
    sdk: flutter
  flutter_app_icon_badge: ^2.0.0
  flutter_dotenv: ^5.0.0
  flutter_emoji: ^2.2.1+1
  flutter_local_notifications: ^9.0.2
  flutter_secure_storage:
    git:
      url: https://github.com/openresearch/flutter_secure_storage
      ref: feature/macos_support
  flutter_slidable: ^0.6.0
  intl: ^0.17.0
  json_serializable: ^6.0.1
  launch_at_login: ^0.0.3
  launch_review: ^3.0.1
  local_auth: ^1.1.8
  package_info: ^2.0.0
  package_info_plus: ^1.0.4
  path_provider: ^2.0.2
  provider: ^6.0.0
  share_plus: ^3.0.2
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.0.0+1
  timeago: ^3.0.2
  toast: ^0.1.5
  url_launcher: ^6.0.9
  uuid: ^3.0.4
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter
  test: ^1.16.8

flutter:
  uses-material-design: false
  assets:
    - images/bell.png
    - images/sad.png
    - .env
    - pubspec.yaml
    - snap/gui/notifi.desktop
  fonts:
    - family: Inconsolata
      fonts:
        - asset: fonts/Inconsolata.ttf
          weight: 400
        - asset: fonts/Inconsolata-Medium.ttf
          weight: 500
        - asset: fonts/Inconsolata-Bold.ttf
          weight: 700
        - asset: fonts/Inconsolata-Black.ttf
          weight: 900
    - family: Akaricons
      fonts:
        - asset: fonts/Akaricons.ttf

flutter_native_splash:
  color: "#f5f5f5"
  image: images/bell.png