name: notifi
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  app_settings: ^4.1.0
  cached_network_image: ^2.2.0+1
  cupertino_icons: ^1.0.2
  dio: ^3.0.10
  f_logs: ^1.2.2
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.15
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.2.0
  flutter_dotenv: ^3.1.0
  flutter_local_notifications: ^4.0.1
  flutter_secure_storage:
    git:
      url: git://github.com/openresearch/flutter_secure_storage.git
      ref: feature/macos_support
  flutter_slidable: ^0.5.7
  fluttericon: ^2.0.0
  intl: ^0.16.0
  json_serializable: ^4.0.1
  launch_at_login: ^0.0.3
  lint: ^1.5.3
  package_info: ^2.0.0
  path_provider: ^1.6.27
  provider: ^5.0.0
  share: ^2.0.1
  shared_preferences: ^0.5.12+4
  sqflite: ^1.3.2+3
  timeago: ^3.0.2
  toast: ^0.1.5
  url_launcher: ^5.5.0
  uuid: ^2.2.2
  web_socket_channel: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/bell.png
    - images/sad.png
    - .env
    - pubspec.yaml

  fonts:
    - family: Inconsolata
      fonts:
        - asset: fonts/Inconsolata.ttf
        - asset: fonts/Inconsolata-Bold.ttf
          weight: 700
        - asset: fonts/Inconsolata-Black.ttf
          weight: 900
    - family: Akaricons
      fonts:
        - asset: fonts/Akaricons.ttf

flutter_icons:
  image_path: 'images/bell.png'
  android: true
  ios: true
  linux: true