pipeline {
    agent {
        docker { image 'node:7-alpine' }
    }
    stages {
        stage('Pre Test'){
            sh 'go version'
            sh 'go get -u github.com/golang/dep/cmd/dep'
            sh 'go get -u github.com/golang/lint/golint'
            sh 'go get github.com/tebeka/go2xunit'
            sh 'cd $GOPATH/src/cmd/project && dep ensure'
        }
        stage('Test'){
            sh """cd $GOPATH && go test"""
        }
    }
}