# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#edit_items.append(EditItem(link_id=link_id, product_id=str(product_id_tag["id"])))

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:mac)

platform :mac do
  desc "Upload build to test flight"
  lane :build do

    # https://docs.fastlane.tools/actions/build_mac_app/
    build_mac_app(
        export_method: "mac-application",
        export_options: {
            provisioningProfiles: {
                "it.notifi.notifi" => "it.notifi.notifi AppStore"
            }
        },
        output_name: "notifi.ipa"
    )
  end
end
