# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#edit_items.append(EditItem(link_id=link_id, product_id=str(product_id_tag["id"])))

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

team_id("Z28DW76Y3W")
default_platform(:mac)

platform :mac do
  lane :keychain do

    create_keychain(
        name: "kc",
        password: "p4ssword",
        default_keychain: false,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
    )

    app_store_connect_api_key(
        key_id: "MK4628AYTK",
        issuer_id: "69a6de80-d5bc-47e3-e053-5b8c7c11a4d1",
        key_filepath: "../AuthKey_MK4628AYTK.p8",
        duration: 1200
    )

    begin
        match(type: "mac_installer_distribution", keychain_name: "kc", keychain_password: "p4ssword")
    rescue => ex
        UI.error(ex)
    end
    match(keychain_name: "kc", keychain_password: "p4ssword")

  end


  lane :build do

    create_keychain(
        name: "my-keychain2",
        password: "p4ssword",
        default_keychain: false,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
    )

    app_store_connect_api_key(
        key_id: "MK4628AYTK",
        issuer_id: "69a6de80-d5bc-47e3-e053-5b8c7c11a4d1",
        key_filepath: "../AuthKey_MK4628AYTK.p8",
        duration: 1200
    )

    match(type: "mac_installer_distribution", keychain_name: "my-keychain2", keychain_password: "p4ssword")

    # https://docs.fastlane.tools/actions/build_mac_app/
    build_mac_app(
        export_options: {
            method: "app-store",
        },
        export_team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    )

    upload_to_app_store
  end
end
