title: notifi
email: hello@notifi.it
recaptcha:
  pub: 6LcbhkgUAAAAAIe6ZSvN9SQ8KaWgLb56xVUK82Ds
  priv: 6LcbhkgUAAAAABuigVIcuHf_9DwOCcifC-ny_IwQ
meta:
  keywords: notifi, notifi it, notify, notification, push notification, curl, mac, osx, mac to mac
  description: Send simple push notifications to your Mac using HTTP.
app:
  version:
    num: 0.001
    description: >
      <h2>New Features</h2>

      <h2>Bugs</h2>

      <h4>Untested Release</h4>
      Thank you for testing!<br><br>
      Maximilian Mitchell
  dmg: notifi.dmg