title: notifi
email: hello@notifi.it
recaptcha:
  pub: 6LcbhkgUAAAAAIe6ZSvN9SQ8KaWgLb56xVUK82Ds
  priv: 6LcbhkgUAAAAABuigVIcuHf_9DwOCcifC-ny_IwQ
meta:
  keywords: notifi, notifi it, notify, notification, push notification, curl, mac, osx, mac to mac
  description: Send simple push notifications to your Mac using HTTP.
app:
  version:
    num: 0.07
    description: >
      <h1>Remove configs from info.plist</h1>
  dmg: notifi.dmg