title: notifi
email: hello@notifi.it
recaptcha:
  pub: 6LcbhkgUAAAAAIe6ZSvN9SQ8KaWgLb56xVUK82Ds
  priv: 6LcbhkgUAAAAABuigVIcuHf_9DwOCcifC-ny_IwQ
meta:
  keywords: notifi, notifi it, notify, notification, push notification, curl, mac, osx, mac to mac
  description: Send simple push notifications to your Mac using HTTP.
app:
  version:
    num: 0.002
    description: >
      <h1>New Features</h1>
      Moved infrastructure to Go.
  dmg: notifi.dmg