proxy:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./socket.conf:/etc/nginx/conf.d/default.conf
  links:
    - ws
    - db

ws:
  build: .
  volumes:
    - ./socket/start.php:/socket/start.php
    - ./secret_server_code.pass:/secret_server_code.pass
    - ./encryption.key:/encryption.key
  links:
    - db

db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: Rn0bHiwNpSN5hpOi6qpTEO8Z
    MYSQL_DATABASE: notifi
    MYSQL_USER: notifi
    MYSQL_PASSWORD: notifi
  volumes:
    - ./sql:/docker-entrypoint-initdb.d/:ro