"""Compose the Mac App Store screenshots from the popover captures.

Same type as appstore-frames.py, turned landscape: Recursive Mono title,
Karla description, the same soft ground ramp.
Three frames mirror the iOS set -- inbox, message, keys -- and each hangs the
popover from a menu bar drawn at the size the capturing Mac's own is: Apple
mark, then bell, Wi-Fi, battery and clock, the glyphs read out of index.html
and the bell out of bell-body.svg and bell-clapper.svg, with the bell over
the popover's arrow. Output is 2560x1600, one of the sizes App Store Connect
accepts for macOS, written to fastlane/screenshots-macos/<locale>/.

The popover artwork comes from `make screens-mac`, which drives the real Mac
app and needs a human at the machine; it leaves the three raw captures in
/tmp/notifi-screens as mac-inbox.png, mac-detail.png and mac-keys.png.

    python3 apps/app/Scripts/appstore-frames-mac.py

Run it from the repo root. It renders every locale in one pass -- the caption
table in fastlane/screenshot-copy.json is generated by `make gen-copy`, and
en-US shares en-GB's English the way fastlane/metadata does.
"""
import json, os, sys
import random
from PIL import Image, ImageChops, ImageDraw, ImageFilter, ImageFont

sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from publish_image import publish
import banner

REPO = os.environ.get("REPO", os.getcwd())
RAW = os.environ.get("RAW", "/tmp/notifi-screens")
ASSETS = f"{REPO}/apps/app/Shared/Assets.xcassets"

with open(f"{REPO}/apps/app/fastlane/screenshot-copy.json") as fh:
    CAPTIONS = json.load(fh)

W, H = 2560, 1600
# The iOS frames' light ground on the right of the split; the red field on
# the left carries its own white ink, and the popover its own dark one.
FG, MUTED, BRAND = "#0A0A0A", "#5A5A5A", "#BC2122"
GROUND_TOP, GROUND_BOTTOM = (0xE8, 0xE8, 0xEB), (0xFC, 0xFC, 0xFD)
BRAND_RGB = (0xBC, 0x21, 0x22)
FG_RGB = (0x0A, 0x0A, 0x0A)
GUTTER = 170
TITLE_SIZE, DESC_SIZE = 108, 54
# The red field owns the left of the page and the popover the right; the
# split is fixed so every locale's frame lines up on the listing.
POPOVER_CENTER_X = 1910
POPOVER_H = 1320
SCALE = POPOVER_H / 1452
# The bar is drawn at the size a real one is. The captures are 2x, so one
# point of the Mac they came from is two of their pixels and PT of the frame's;
# every measurement below is that Mac's own bar, read off a screencapture of it
# in points. The bar the site's .mac-bar inherited from the launch film is a
# stylised one -- its glyphs are half again too big for its height, which on a
# frame beside the real popover reads as a bar with no air in it.
PT = 2 * SCALE
BAR_H = round(33 * PT)
# The inset the Apple mark keeps from the left edge and the clock from the
# right, and the air between one status item's ink and the next -- the clock
# stands further off than the icons do.
BAR_PAD = round(20 * PT)
BAR_GAP = round(20 * PT)
CLOCK_GAP = round(24 * PT)
# Each glyph is rasterised to a width, and the widths here are the ones whose
# ink comes out the size the real bar's does: Apple 12x15, bell 14.5x16,
# Wi-Fi 17x12, battery 25.5x12, all in points.
APPLE_W = round(19.7 * PT)
BELL_W = round(16 * PT)
WIFI_W = round(17 * PT)
BATT_W = round(26.6 * PT)
CLOCK_SIZE = round(13 * PT)
SITE = f"{REPO}/apps/api/public"
SYSTEM_FONT = "/System/Library/Fonts/SFNS.ttf"

# The banner is drawn rather than exported -- see banner.py for why. It sits on
# the red field under the caption rather than on the desktop beside the Mac:
# there it is read with the words that explain it, and the Mac keeps the height
# it was giving up to make room. Light, because the field behind it is dark
# enough that a dark banner would disappear into it.
BANNER_MODE = "light"
# The system's own word, left in English like the clock beside it: it is macOS
# chrome rather than the product's copy, and there is no key for it to come from.
BANNER_WHEN = "now"
BANNER_ICON = f"{ASSETS}/AppIcon.appiconset/mac-1024.png"
# The air between the caption and the banner under it.
BANNER_GAP = 72
POPOVER_PT = 461

# The fifth field says whether the frame carries a banner above its bar. Only
# the first frame does -- it is the shot that has to say what the app does, and
# on the other two the banner would push the screen being shown off centre for
# nothing.
FRAMES = [
    ("mac-inbox.png", "inboxTitleIpad", "inboxBody", "01_inbox.png", True),
    ("mac-detail.png", "messageTitle", "messageBody", "02_message.png", False),
    ("mac-keys.png", "keysTitle", "keysBody", "03_keys.png", False),
]


def dehinted(name, out_dir):
    """Same fix as appstore-frames.py: both brand fonts carry TrueType hinting
    FreeType renders wrong at these sizes, and at 40px+ the hints buy nothing."""
    from fontTools.ttLib import TTFont
    from fontTools.ttLib.tables import ttProgram

    out = f"{out_dir}/.{name}.ttf"
    font = TTFont(f"{REPO}/apps/app/Shared/Fonts/{name}.ttf")
    for table in ("fpgm", "prep", "cvt ", "gasp"):
        if table in font:
            del font[table]
    glyf = font["glyf"]
    for glyph_name in glyf.keys():
        glyph = glyf[glyph_name]
        if hasattr(glyph, "program"):
            empty = ttProgram.Program()
            empty.fromBytecode(b"")
            glyph.program = empty
    font.save(out)
    return out


def wrap(draw, text, font, width):
    lines, line = [], ""
    for word in text.split():
        trial = f"{line} {word}".strip()
        if draw.textlength(trial, font=font) <= width or not line:
            line = trial
        else:
            lines.append(line)
            line = word
    if line:
        lines.append(line)
    return lines


def ground(popover_box):
    ramp = Image.new("RGB", (1, H))
    px = ramp.load()
    for y in range(H):
        t = y / (H - 1)
        px[0, y] = tuple(
            round(a + (b - a) * t) for a, b in zip(GROUND_TOP, GROUND_BOTTOM)
        )
    page = ramp.resize((W, H), Image.BICUBIC).convert("RGBA")

    bloom = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    ImageDraw.Draw(bloom).ellipse(
        [popover_box[0] - 220, popover_box[3] - 260,
         popover_box[2] + 220, popover_box[3] + 200],
        fill=BRAND_RGB + (26,),
    )
    page.alpha_composite(bloom.filter(ImageFilter.GaussianBlur(160)))
    return page


def load_popover(name):
    path = f"{RAW}/{name}"
    if not os.path.exists(path):
        sys.exit(f"{path} is missing -- run `make screens-mac` first")
    shot = Image.open(path).convert("RGBA")
    # The capture carries its own shape in the alpha channel -- rounded panel
    # plus the arrow -- so no rounding or bezel ring is drawn here.
    return shot.resize((round(shot.width * SCALE), POPOVER_H), Image.LANCZOS)


def rasterize(svg, width, tint, out_dir, name):
    """rsvg-convert renders an SVG string at a pixel width; the result is
    used as a mask and filled with the tint, which is what the site's CSS
    mask-image does with the same files."""
    import subprocess
    path = f"{out_dir}/.{name}.png"
    subprocess.run(["rsvg-convert", "-w", str(width), "-o", path],
                   input=svg.encode(), check=True)
    art = Image.open(path).convert("RGBA")
    os.remove(path)
    layer = Image.new("RGBA", art.size, tint + (0,))
    layer.putalpha(art.getchannel("A"))
    return layer


def site_svg(cls):
    """The bar's marks are the landing page's own: the inline SVGs the
    .mac-apple, .mac-wifi and .mac-batt classes carry in index.html."""
    import re
    html = open(f"{SITE}/index.html").read()
    m = re.search(rf'<svg class="{cls}"[^>]*>.*?</svg>', html, re.S)
    if not m:
        sys.exit(f"index.html no longer carries an <svg class=\"{cls}\">")
    svg = m.group(0).replace('fill="currentColor"', 'fill="#fff"')
    svg = svg.replace('stroke="currentColor"', 'stroke="#fff"')
    return svg.replace("<svg ", '<svg xmlns="http://www.w3.org/2000/svg" ', 1)


def bell(out_dir):
    """The site's .bell: bell-body.svg and bell-clapper.svg stacked, both
    cropped by the same box by generate-marks.sh."""
    size = BELL_W
    icon = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    for part in ("bell-body", "bell-clapper"):
        layer = rasterize(open(f"{SITE}/{part}.svg").read(), size, FG_RGB, out_dir, part)
        icon.alpha_composite(layer, (0, (size - layer.height) // 2))
    return icon


def slide_arrow(popover, to_x):
    """screens-mac.sh does the same for the site: the arrow sits wherever the
    screen edge pushed it, and the panel's top edge is uniform, so the arrow
    can be moved along it seamlessly to sit under the bell."""
    alpha = popover.getchannel("A").load()
    w, h = popover.size

    def span(y):
        xs = [x for x in range(w) if alpha[x, y] > 8]
        return (min(xs), max(xs)) if xs else None

    apex_y = next(y for y in range(h) if span(y))
    panel_top = next(y for y in range(apex_y, h)
                     if (sp := span(y)) and sp[1] - sp[0] > w * 0.5)
    ax0, ax1 = span(panel_top - 1)
    pad = 10
    # The panel's own first row carries the junction with the arrow, baked in
    # where the arrow met it, so it travels with the arrow; the row it leaves
    # behind is repaired with a stretch of plain panel edge from beside it.
    box = (ax0 - pad, apex_y, ax1 + pad + 1, panel_top + 1)
    arrow = popover.crop(box)
    width = box[2] - box[0]
    clean_x = box[0] - width - 30 if box[0] - width - 30 > 0 else box[2] + 30
    edge = popover.crop((clean_x, panel_top, clean_x + width, panel_top + 1))
    # The arrow is translucent, so the capture baked the wallpaper behind it
    # into its colour. Only its solid core is repainted with the panel's own
    # colour; the soft edge is the window's shadow and is left as captured.
    panel = popover.getpixel(((ax0 + ax1) // 2, panel_top + 4))[:3]
    alpha_band = arrow.getchannel("A")
    core = alpha_band.point(lambda v: 255 if v > 200 else 0)
    arrow = Image.composite(Image.new("RGBA", arrow.size, panel + (255,)),
                            arrow, core)
    arrow.putalpha(alpha_band)
    moved = popover.copy()
    moved.paste((0, 0, 0, 0), box)
    moved.paste(edge, (box[0], panel_top))
    dx = round(to_x - (ax0 + ax1 + 1) / 2)
    moved.paste(arrow, (box[0] + dx, box[1]), arrow)
    return moved, panel_top


def bar_time():
    """The time on the bar is the time the popover under it was captured, which
    screens-mac.sh writes down beside the captures. A hard-coded clock said
    14:07 over an inbox whose newest notification was stamped 15:05, and beside
    a banner saying "now"."""
    path = f"{RAW}/clock.txt"
    if not os.path.exists(path):
        sys.exit(f"{path} is missing -- run `make screens-mac` first")
    return open(path).read().strip()


def menu_bar(canvas, desk, out_dir):
    """The bar across the top of the popover: frosted white over the ground,
    the Apple mark at the left, and the status items right-aligned -- bell,
    Wi-Fi, battery, clock.
    Returns the bell's centre x, which the popover's arrow then meets."""
    x0, y0, x1, _ = desk
    width = x1 - x0
    bar = Image.new("RGBA", (width, BAR_H), (255, 255, 255, 170))
    canvas.alpha_composite(bar, (x0, y0))
    d = ImageDraw.Draw(canvas)

    apple = rasterize(site_svg("mac-apple"), APPLE_W, FG_RGB, out_dir, "apple")
    apple.putalpha(apple.getchannel("A").point(lambda v: v * 85 // 100))
    canvas.alpha_composite(apple, (x0 + BAR_PAD, y0 + (BAR_H - apple.height) // 2))

    icon = bell(out_dir)
    wifi = rasterize(site_svg("mac-wifi"), WIFI_W, FG_RGB, out_dir, "wifi")
    batt = rasterize(site_svg("mac-batt"), BATT_W, FG_RGB, out_dir, "batt")
    clock = ImageFont.truetype(SYSTEM_FONT, CLOCK_SIZE)
    try:
        clock.set_variation_by_name("Medium")
    except OSError:
        pass
    text = bar_time()
    tb = d.textbbox((0, 0), text, font=clock)
    cluster = (icon.width + BAR_GAP + wifi.width + BAR_GAP + batt.width
               + CLOCK_GAP + (tb[2] - tb[0]))

    x = x1 - BAR_PAD - cluster
    bell_x = x + icon.width / 2
    canvas.alpha_composite(icon, (x, y0 + (BAR_H - icon.height) // 2))
    x += icon.width + BAR_GAP
    canvas.alpha_composite(wifi, (x, y0 + (BAR_H - wifi.height) // 2))
    x += wifi.width + BAR_GAP
    canvas.alpha_composite(batt, (x, y0 + (BAR_H - batt.height) // 2))
    x += batt.width + CLOCK_GAP
    d.text((x, y0 + (BAR_H - (tb[3] - tb[1])) // 2 - tb[1]), text, font=clock, fill=FG)
    return bell_x


SPLIT = 1200
RED_RGB = (0xBC, 0x21, 0x22)
MARK = 150


def frame(locale, captions, title_key, desc_key, popover, out_dir, out_name,
          with_banner):
    # The bar and the popover, nothing around them: the desk is the site's
    # .mac-desk width so the bar keeps its proportions, but it carries no
    # border and no ground below the popover. Centred on the right half.
    desk_w = round(popover.width / 0.94)
    desk_h = BAR_H + popover.height
    desk_x = POPOVER_CENTER_X - desk_w // 2
    # The banner stands above the bar rather than over the screen, so it is
    # part of the stack and not something laid on top of one: the desk drops by
    # the banner's height and the pair is centred together, which keeps the
    # popover off the frame's edge whatever the banner's aspect turns out to be.
    desk_y = (H - desk_h) // 2
    desk = [desk_x, desk_y, desk_x + desk_w, desk_y + desk_h]
    left = desk_x + (desk_w - popover.width) // 2
    top = desk_y + BAR_H
    box = [left, top, left + popover.width, top + popover.height]

    canvas = ground(box)
    d = ImageDraw.Draw(canvas)
    # The left field is the brand red, edge to edge, carrying the mark and
    # the caption in white; the popover keeps the light ground on the right.
    # The grain is the site's: noise seeded so the field is the same every
    # run, overlaid at half strength so it reads as paper, not as dither.
    random.seed(7)
    field = Image.new("RGB", (SPLIT, H), RED_RGB)
    # Drawn at half size and doubled: a one-pixel grain at 2560 wide is gone
    # the moment the listing scales the frame down.
    grain = Image.effect_noise((SPLIT // 2, H // 2), 26)
    # Only the specks above the midpoint are kept, so the field is flecked
    # lighter and never darker.
    grain = grain.point(lambda v: max(v, 128))
    grain = grain.resize((SPLIT, H), Image.NEAREST).convert("RGB")
    field = ImageChops.overlay(field, grain)
    canvas.paste(field, (0, 0))

    mono = dehinted("RecursiveMono-SemiBold", out_dir)
    sans = dehinted("Karla", out_dir)

    tf = ImageFont.truetype(mono, TITLE_SIZE)
    try:
        tf.set_variation_by_name("Bold")
    except OSError:
        pass
    df = ImageFont.truetype(sans, DESC_SIZE)
    try:
        df.set_variation_by_name("Regular")
    except OSError:
        pass

    mark = Image.new("RGBA", (MARK, MARK), (0, 0, 0, 0))
    for part in ("bell-body", "bell-clapper"):
        layer = rasterize(open(f"{SITE}/{part}.svg").read(), MARK, (255, 255, 255), out_dir, part)
        mark.alpha_composite(layer, (0, (MARK - layer.height) // 2))

    title_lines = []
    for para in captions[title_key].split("\n"):
        title_lines += wrap(d, para, tf, SPLIT - GUTTER * 2)
    desc_lines = wrap(d, captions[desc_key], df, SPLIT - GUTTER * 2)
    banner_w = SPLIT - GUTTER * 2
    block_h = (MARK + 64
               + len(title_lines) * round(TITLE_SIZE * 1.14)
               + 56
               + len(desc_lines) * round(DESC_SIZE * 1.48))
    if with_banner:
        block_h += BANNER_GAP + banner.height_for(banner_w)
    y = (H - block_h) // 2
    canvas.alpha_composite(mark, (GUTTER, y))
    y += MARK + 64
    for line in title_lines:
        d.text((GUTTER, y), line, font=tf, fill="#FFFFFF")
        y += round(TITLE_SIZE * 1.14)
    y += 56
    for line in desc_lines:
        d.text((GUTTER, y), line, font=df, fill=(255, 222, 222))
        y += round(DESC_SIZE * 1.48)

    if with_banner:
        banner.draw(canvas, GUTTER, y + BANNER_GAP, banner_w, BANNER_MODE,
                    captions["bannerTitle"], captions["bannerBody"],
                    BANNER_WHEN, BANNER_ICON)

    bell_x = menu_bar(canvas, desk, out_dir)

    popover, panel_row = slide_arrow(popover, bell_x - left)

    # .mac-wall .mac-shot: drop-shadow(0 18px 36px rgba(0,0,0,.55)), at 2x,
    # following the popover's own alpha, arrow and all.
    # Cast from the panel alone, not the arrow: blurred by 36 the arrow's own
    # shadow rises above the panel edge and haloes the arrow.
    shadow = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    silhouette = Image.new("RGBA", popover.size, (18, 18, 24, 96))
    body = popover.getchannel("A").point(lambda v: v * 96 // 255)
    body.paste(0, (0, 0, popover.width, panel_row))
    silhouette.putalpha(body)
    shadow.alpha_composite(silhouette, (left, top + 36))
    canvas.alpha_composite(shadow.filter(ImageFilter.GaussianBlur(36)))
    canvas.alpha_composite(popover, (left, top))

    publish(canvas.convert("RGB"), f"{out_dir}/{out_name}", "PNG")

    for tmp in (mono, sans):
        os.remove(tmp)


popovers = {raw: load_popover(raw) for raw, _, _, _, _ in FRAMES}
for locale, caption_key in [("en-US", "en-GB"), ("en-GB", "en-GB"),
                            ("de-DE", "de-DE"), ("es-ES", "es-ES"),
                            ("fr-FR", "fr-FR"), ("it", "it")]:
    out_dir = f"{REPO}/apps/app/fastlane/screenshots-macos/{locale}"
    os.makedirs(out_dir, exist_ok=True)
    stale = f"{out_dir}/01_popover.png"
    if os.path.exists(stale):
        os.remove(stale)
    for raw, title_key, desc_key, out_name, with_banner in FRAMES:
        frame(locale, CAPTIONS[caption_key], title_key, desc_key,
              popovers[raw], out_dir, out_name, with_banner)
