platform :osx, '10.12'
target 'notifi' do
  pod 'SocketRocket'
  pod 'SDWebImage'
  pod 'SAMKeychain'
  pod 'Sparkle'
  pod 'STHTTPRequest'
  pod 'CocoaLumberjack'
#  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git'
  use_frameworks!
end
