# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#edit_items.append(EditItem(link_id=link_id, product_id=str(product_id_tag["id"])))

update_fastlane

default_platform(:ios)
cocoapods(
    clean_install: true,
)

platform :ios do
  desc "Upload build to test flight"
  lane :tfdeploy do
    create_keychain(
        name: "kc",
        password: "p4ssword",
        default_keychain: false,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
    )

    app_store_connect_api_key(
        key_id: "MK4628AYTK",
        issuer_id: "69a6de80-d5bc-47e3-e053-5b8c7c11a4d1",
        key_filepath: "../AuthKey_MK4628AYTK.p8",
        duration: 1200
    )

    match(type: "development", readonly: true, keychain_name: "kc", keychain_password: "p4ssword")
    match(type: "appstore", readonly: true, keychain_name: "kc", keychain_password: "p4ssword")

    build_app(
      workspace: "Runner.xcworkspace",
      export_method: "app-store",
      xcargs: {
        PROVISIONING_PROFILE_SPECIFIER: ENV["sigh_it.notifi.notifi_appstore"]
      }
    )
    upload_to_testflight
  end

  desc "Upload build to app store"
  lane :asdeploy do
    create_keychain(
        name: "kc",
        password: "p4ssword",
        default_keychain: false,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
    )

    app_store_connect_api_key(
        key_id: "MK4628AYTK",
        issuer_id: "69a6de80-d5bc-47e3-e053-5b8c7c11a4d1",
        key_filepath: "../AuthKey_MK4628AYTK.p8",
        duration: 1200
    )

    match(type: "development", readonly: true, keychain_name: "kc", keychain_password: "p4ssword")
    match(type: "appstore", readonly: true, keychain_name: "kc", keychain_password: "p4ssword")

    build_app(
      workspace: "Runner.xcworkspace",
      export_method: "app-store",
      xcargs: {
        PROVISIONING_PROFILE_SPECIFIER: ENV["sigh_it.notifi.notifi_appstore"]
      }
    )
    upload_to_app_store(
        force: true,
        skip_screenshots: true,
        submit_for_review: true,
        automatic_release: true,
        precheck_include_in_app_purchases: false,
        submission_information: {
          export_compliance_platform: 'ios',
          export_compliance_compliance_required: false,
          export_compliance_encryption_updated: false,
          export_compliance_app_type: nil,
          export_compliance_uses_encryption: false,
          export_compliance_is_exempt: false,
          export_compliance_contains_third_party_cryptography: false,
          export_compliance_contains_proprietary_cryptography: false,
          export_compliance_available_on_french_store: false
        }
    )
  end
end
