# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#edit_items.append(EditItem(link_id=link_id, product_id=str(product_id_tag["id"])))

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Upload build to test flight"
  lane :tfdeploy do
    build_ios_app(
        export_method: "app-store",
        export_options: {
            provisioningProfiles: {
                "it.notifi.notifi" => "iOS App Store"
            }
        }
    )
    upload_to_testflight
  end

  desc "Upload build to app store"
  lane :asdeploy do
    build_ios_app(
        export_method: "app-store",
        export_options: {
            provisioningProfiles: {
                "it.notifi.notifi" => "iOS App Store"
            }
        }
    )
    upload_to_app_store
  end
end
