name: notifi
version: 0.0.1
summary: Push notifications over HTTP
description: A multi platform app to receive push notifications over simple HTTP requests you can embed anywhere.
confinement: strict
base: core18
grade: stable

slots:
  dbus-notifi:
    interface: dbus
    bus: session
    name: it.notifi

apps:
  notifi:
    command: notifi
    extensions: [flutter-dev]
    plugs:
      - network
    slots:
      - dbus-notifi

parts:
  notifi:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
    stage-packages:
      # packages required to run
      - libsecret-1-dev
      - libjsoncpp1
      - libsqlite3-0
      - libsqlite3-dev