name: MacOS
on: [ push, pull_request ]

jobs:
  version:
    name: "Get Version"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - id: bump_version
        if: ${{ github.ref == 'refs/heads/master' || (!github.event.issue.pull_request && github.ref == 'refs/heads/develop') }}
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: master
          DRY_RUN: true
      - id: version
        name: Create Version
        run: |
          if [ -n "${{ steps.bump_version.outputs.new_tag }}" ]
          then
            echo ::set-output name=VERSION::${{ steps.bump_version.outputs.new_tag }}
          else
            echo ::set-output name=VERSION::$GITHUB_RUN_ID
          fi

  checks:
    name: "Lint & Test"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - name: "Lint"
        run: |
          touch .env
          flutter analyze
      - name: "Test"
        run: flutter test
      - name: "Upload failure Screenshots"
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: golden-failures
          path: test/failures

  #########
  # macos #
  #########
  build-macos:
    name: "Build MacOS"
    runs-on: macos-latest
    needs: version
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - name: "Build"
        run: |
          flutter config --enable-macos-desktop
          flutter pub get
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]
          then
            echo "${{ secrets.B64_DEV_ENV }}" | base64 --decode > .env
          else
            echo "${{ secrets.B64_ENV }}" | base64 --decode > .env
          fi
          flutter build macos --release --build-name=${{ needs.version.outputs.version }}
      - name: "Codesign"
        run: |
          echo ${{ secrets.MACOS_CERTIFICATE }} | base64 --decode > certificate.p12
          security create-keychain -p p4ssword build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p p4ssword build.keychain
          security import certificate.p12 -k build.keychain -P ${{ secrets.MACOS_CERTIFICATE_PWD }} -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k p4ssword build.keychain
          /usr/bin/codesign --force --deep -s Z28DW76Y3W build/macos/Build/Products/Release/notifi.app
      - name: "Create .dmg"
        run: |
          npm install --global create-dmg
          mkdir dmg
          create-dmg build/macos/Build/Products/Release/notifi.app dmg/
      - name: "Store .dmg artifact"
        uses: actions/upload-artifact@v2
        with:
          name: notifi-dmg
          path: dmg/
          if-no-files-found: error

  deploy-macos:
    name: "Deploy MacOS"
    if: ${{ github.ref == 'refs/heads/master' || (!github.event.issue.pull_request && github.ref == 'refs/heads/develop') }}
    runs-on: macos-latest
    needs: [ checks, build-macos, version ]
    steps:
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: notifi-dmg
      - name: "Deploy .dmg as GH release"
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: ${{ github.ref == 'refs/heads/develop' }}
          automatic_release_tag: ${{ needs.version.outputs.version }}
          title: "Release ${{ needs.version.outputs.version }}"
          files: |
            ${{steps.download.outputs.download-path}}

  #########
  #  iOS  #
  #########
  build-ios:
    name: "Build & Deploy iOS"
    runs-on: macos-latest
    needs: [ version ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      - name: "Build"
        run: |
          flutter pub get
          if [[ "${{ github.ref }}" != "refs/heads/master" ]]
          then
            echo "${{ secrets.B64_DEV_ENV }}" | base64 --decode > .env
            cd ios

            if [[ "${{ github.ref }}" == "refs/heads/develop" ]]
            then
              xcrun agvtool new-version -all ${{ needs.version.outputs.version }}
            else
              xcrun agvtool new-version -all 0.0.$GITHUB_RUN_ID
            fi
          else
            echo "${{ secrets.B64_ENV }}" | base64 --decode > .env
            cd ios
            xcrun agvtool new-version -all ${{ needs.version.outputs.version }}
          fi
          pod install

      - name: "Setup codesign keychain"
        run: |
          echo ${{ secrets.MACOS_CERTIFICATE }} | base64 --decode > certificate.p12
          security create-keychain -p p4ssword build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p p4ssword build.keychain
          security import certificate.p12 -k build.keychain -P ${{ secrets.MACOS_CERTIFICATE_PWD }} -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k p4ssword build.keychain

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo ${{ secrets.PROVISIONING_PROFILE_DATA }} | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

      - name: "Run fastlane"
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        run: |
          cd ios
          gem install fastlane

          if [[ "${{ github.ref }}" == "refs/heads/master" ]]
          then
            fastlane appstore
          else
            fastlane tfdeploy
          fi
