name: notifi
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - run: |
          echo "${{ secrets.B64_ENV }}" | base64 --decode > .env
          flutter build macos --release
      - uses: actions/upload-artifact@v2
        with:
          name: macos-build
          path: build/macos/Build/Products/Release/