name: notifi
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - name: Run flutter build macos
        run: |
          echo "${{ secrets.B64_ENV }}" | base64 --decode > .env
          flutter build macos --release
      - name: Create dmg
        continue-on-error: true
        run: |
          npm install --global create-dmg
          mkdir dmg
          ls build/macos/Build/Products/Release/notifi.app
          create-dmg build/macos/Build/Products/Release/notifi.app dmg/
      - uses: actions/upload-artifact@v2
        with:
          name: notifi-dmg
          path: dmg/